name: PDX 4Seasons Nail Spa
favicon: null
layout_spectrum: 0.27854
typography_spectrum: 0.55216
title: pdx 4seasons nail spa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00f339'
    - '#00b14b'
    - '#67f552'
    - '#4ecb84'
  brandStrength: 0.748218237888068
  lightness: 0.25168234924785793
  saturation: 0.12925008730962873
  rhythmicContrast: 0.7082108967006207
purpose: []
