name: PDX 4Seasons Nail Spa
favicon: null
layout_spectrum: 0.27854
typography_spectrum: 0.25492
title: pdx 4seasons nail spa
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00f339'
    - '#00b14b'
    - '#67f552'
    - '#4ecb84'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
